### ISSUE TITLE
XGBSEDebiasedBCE n_jobs parameter

### ISSUE THREAD

**Issue by kmedved** [loft-br/xgboost-survival-embeddings#11]
I'm curious to understand how the `XGBSEDebiasedBCE` (and perhaps other modules') `n_jobs` parameter works. I see it listed here: https://loft-br.github.io/xgboost-survival-embeddings/bce.html as a separate parameter from the xgboost parameters themselves (which has it's own `n_jobs` parameter). 

Does this parameter impact the logistic regression instead of xgboost? In other words, what is being multiprocessed here?

Perhaps relatedly, I've noticed that the xgboost part of `XGBSEDebiasedBCE` will typically fit quite quickly on my data (~20 seconds if using GPU and stopping after about 150 rounds), but will then pause for 30-40 seconds before the fitting is complete. Is this due to the logistic regression that `XGBSEDebiasedBCE` is performing after fitting with xgboost and is there any good way to speed this up?

**Comment by gdmarmerola-loft** [comment]
Hey @kmedved, thanks for opening the issue!

You're correct. The separate `n_jobs` parameter defines how many CPU cores will be used to fit the multiple logistic regressions. We fit them with a simple joblib loop (in `xgbse/debiased_bce.py`):

```python
with Parallel(n_jobs=self.n_jobs) as parallel:
    lr_estimators = parallel(
        delayed(self._fit_one_lr)(leaves_encoded, targets[:, i])
        for i in range(targets.shape[1])
    )
```

We're working on ideas to try to make the process more efficient. I can think of two ways to improve this. The most promising is to use a multi-task logistic regression approach, so we maintain multiple outputs but fit only one model. I think the most straightforward way to do this is via `torch`, which opens up the possibility of unlocking GPUs across the board. The drawback is to have torch as a dependency to the lib.

The second alternative is to still use multiple logistic regressions, but trying different solvers, including the [SGDClassifier](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.SGDClassifier.html) approach.

**Comment by gdmarmerola-loft** [comment]
Anyway, will check the docs and add these improvements to our roadmap! Thank you very much for the feedback!

**Comment by gdmarmerola-loft** [comment]
Hey @kmedved !

We just shipped [`XGBSEStackedWeibull`](https://loft-br.github.io/xgboost-survival-embeddings/modules/stacked_weibull.html), which is similar to `XGBSEDebiasedBCE` but fits a single Weibull AFT Regression using the predicted risk from XGBoost. It is a lot faster than BCE, with comparable results! We invite you to give it a try.

We also improved the `XGBSEDebiasedBCE` [documentation](https://loft-br.github.io/xgboost-survival-embeddings/modules/bce.html) and added a call-out that warns that Logistic Regressions may become a bottleneck.

We're also working on making the Logistic Regression estimation more efficent.

Thank you for your feedback!

**Comment by kmedved** [comment]
Thank you for this addition @GabrielGimenez. I have been experimenting with Weibull AFT, and the results look promising so far, although I am still figuring out which parameters are most important to tune (on the Xgboost side and the Lifelines side).

With respect to `XGBSEDebiasedBCE`, take my view at a grain of salt, but I think it's better to avoid adding a `Torch` dependency if it can be avoided. It's slower to fit, but with the availability of `XGBSEStackedWeibull` users have both options available either way.
