### ISSUE TITLE
Underlying xgboost model for calculating feature importances

### ISSUE THREAD

**Issue by kmedved** [loft-br/xgboost-survival-embeddings#14]
Xgboost models can output [permutation or gain feature importances](https://xgboost.readthedocs.io/en/latest/python/python_api.html). Additionally, through packages such as [Shap](https://github.com/slundberg/shap), it's possible to get Shapley values for Xgboost models, which can be highly informative about what features are contributing to survival.

It would be helpful to allow the user to access the underlying Xgboost regressor object in order to calculate/view these feature importance. I don't know if this is already possible in some way, but if not, exposing this to the user would be helpful.

**Comment by GabrielGimenez** [comment]
You can access the xgboost estimator using the model.bst and use it with shap or acess feature importance directly using model.bst.get_score too. 

But i agree that feature importance should be available directly, will keep this issue for a future enhancement.

**Comment by kmedved** [comment]
Perfect. I didn't realize we had access to the xgboost estimator directly.
