### ISSUE TITLE
Multi-states and competing risk modelling

### ISSUE THREAD

**Issue by matdeof** [loft-br/xgboost-survival-embeddings#29]
Hello guys, first of all congratulations for your work :) 

Currently I'm facing a multi-state modeling with multiple absorbing states, in the search of some techniques I found this module. As far as I could go into the docs I didn't find any mention to multi-states and competing risks modelling, does my understanding is correct?

If so, do you guys intend to extend the use cases of this module in that direction?

Thanks!

**Comment by davivieirab** [comment]
Hey @matdeof , thank you for your message!

Yes, you are correct. The current xgbse implementation only covers tradicional two-state models (alive - death). We have a roadmap of improvement, but this use case is not yet covered. We will add this topic as a potential future enhancement.

Although that is the case, we invite you to contribute to our module. We are open to suggestions of strategies that encompass this group of models. Also, feel free to create a PR if you have an idea of implementation to add to the current xgbse stack.

One more time, thank you for the suggestions!

**Comment by matdeof** [comment]
Got it @davivieirab!

Thank you for sharing the context! 

I'm still learning more about the field and exploring the current available techniques, if I get to a point of making those contributions I would definitely be glad about making them :)
