### ISSUE TITLE
Cure Fraction Problem?

### ISSUE THREAD

**Issue by isaachaberman** [loft-br/xgboost-survival-embeddings#35]
What is the "cure fraction" problem described in the documentation for the `XGBSEStackedWeibull`.  To quote:
```We also have better extrapolation capabilities, as opposed to the cure fraction problem in `XGBSEKaplanNeighbors` and `XGBSEKaplanTree`. ```

**Comment by GabrielGimenez** [comment]
`XGBSEKaplanNeighbors` and `XGBSEKaplanTree`can't iterate over times that has no sample, so if you dataset has a high cure fraction you might end over the median even at the last time. 

`XGBSEStackedWeibull` is a parametric method, so it can predict even at times you dataset has no observations, so we say it can naturally extrapolates your results to the time intervals that you want
