### ISSUE TITLE
Adding DOI for Citation

### ISSUE THREAD

**Issue by BardiaKh** [loft-br/xgboost-survival-embeddings#50]
I would like to thank you for the hard work you put into developing this package.

I used your work in my research and wanted to cite it in the manuscript. I saw you have a reference manual but unfortunately, it does not have DOI. I was wondering if you could list your package on [zendono](https://zenodo.org/) so that you can have a DOI for xgbse?

This would facilitate referring to your work for many journals.

**Comment by gdmarmerola-loft** [comment]
Thank you for your suggestion, @BardiaKh!

Just created the DOI and added the badge to the README: 

10.5281/zenodo.6326018

Hope this helps!!!
