### ISSUE TITLE
How can we get the importance and output trees?

### ISSUE THREAD

**Issue by sqf10000** [loft-br/xgboost-survival-embeddings#52]
XGBSEDebiasedBCE.plot_importance(xgbse_model)
AttributeError: type object 'XGBSEDebiasedBCE' has no attribute 'plot_importance'

Can you add the plot_importance function in your xgbse?

**Comment by GabrielGimenez** [comment]
Hi! We are discussing how to make the internal xgboost model easier to use, but for now, you can get feature importance using 
`xgbse_model.bst.get_score(importance_type='gain')`
