### ISSUE TITLE
XGBEmbedKaplanNeighbors appears to now be XGBSEKaplanNeighbors 

### ISSUE THREAD

**Issue by kmedved** [loft-br/xgboost-survival-embeddings#7]
Hello - thanks for this amazing library. It's truly a life-saver after looking around for a modern survival analysis library which could handle both large data, as well provide the full survival curve for every row. You've built something special here.

In exploring, I discovered that the `XGBEmbedKaplanNeighbors` import in the documentation should now be a `XGBSEKaplanNeighbors` import, if I'm reading things correctly. I don't know if any other class names have changed, but wanted to flag to help get more people using this library.

(Unrelatedly, I was unable to install this package in Colab due to a claimed dependency on Python 3.6.9. However, it worked fine on my local machine on 3.8).

Thanks again for the great work. I look forward to exploring the functionality more.

**Comment by GabrielGimenez** [comment]
Hi, thank you for your report! 
We're working in breaking the basic usage session of the documentation into smaller parts, this will be updated too.

About colab, I belive colab runs on python 3.6.9 and we require >= 3.7. Maybe there's a way to run a more recent version of python on colab?

**Comment by kmedved** [comment]
Thanks. It looks like I misunderstood and reversed the error message in Colab (thinking Colab was on 3.7 and xgbse wanted 3.6.9). 

Excited for further documentation improvements. Thanks.

**Comment by GabrielGimenez** [comment]
Hey @kmedved, just to let you know that we updated a few examples and the read me. Feel free to open new issues regarding documentation or any other problems you find

**Comment by kmedved** [comment]
Thank you @GabrielGimenez - I appreciate all the work on this.

**Comment by brianleegit** [comment]
Hi wondering will there be any support on python 3.6 ?
