### ISSUE TITLE
update pandas version requirement

### ISSUE THREAD

**Issue by Yimin-Yi** [loft-br/xgboost-survival-embeddings#70]
Hi team, when installing this package, it says

> DEPRECATION: xgbse 0.2.3 has a non-standard dependency specifier pandas>=1.0.*. pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of xgbse or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063

Since `pandas` has been updated to 2.0+, could we upgrade the required pandas version?

I made a fork and changed the required pandas version (`"pandas>=1.0.0"`), and it works fine for me (`pip` installed `pandas` 2.0.3 while installing `xgbse`).

**Comment by DrShushen** [comment]
@gdmarmerola-loft any chance this small update could be implemented so as to keep the library up to date for `pip`?
