### ISSUE TITLE
Requested xgbse (from synthcity) has invalid metadata: .* suffix can only be used with `==` or `!=` operators     pandas (>=1.0.*)

### ISSUE THREAD

**Issue by MarsMDK** [loft-br/xgboost-survival-embeddings#72]
### Instructions
- In the setup.py metadata, please remove the asterisk on the pandas version requirements.

### Problem description
When installing synthcity the installation of the required xgbse fails because of invalid metadata

**Comment by ajvish91** [comment]
Hi, any updates on this issue?

**Comment by GabrielGimenez** [comment]
@DrShushen That's still happening? We are using poetry to manage the dependencies now and it doesn't have the "*" anymore.

**Comment by DrShushen** [comment]
Please let me double check this, will get back to you in a moment

**Comment by DrShushen** [comment]
Ah @GabrielGimenez - I see what happened. You updated python requirement to 3.9+, and I was using a 3.8 environment. On python 3.9 it pip installs just fine now (xgbse version 0.3.1). I will update dependencies and setup config in the libraries I maintain to resolve this. Thank you for resolving that issues - xgbse is a great library

**Comment by DrShushen** [comment]
So this can be closed now, I think
