### ISSUE TITLE
XGBoost Nrounds Parameter

### ISSUE THREAD

**Issue by kmedved** [loft-br/xgboost-survival-embeddings#8]
Thanks again for the wonderful package. I'm wondering what the best way to set the `nrounds` parameter in the underlying Xgboost model is? I have tried `nrounds`, `n_estimators`, and `num_boost_round`. and gotten the following warning each time:

```
[08:18:45] WARNING: C:\Users\Administrator\workspace\xgboost-win64_release_1.2.0\src\learner.cc:516: 
Parameters: { num_boost_round } might not be used.

  This may not be accurate due to some parameters are only used in language bindings but
  passed down to XGBoost core.  Or some parameters are not used but slip through this
  verification. Please open an issue if you find above cases.
```

What's the correct interface for this?

**Comment by GabrielGimenez** [comment]
Should be the parameter `num_boost_round` on `fit` for all modules except XGBSEKaplanTree
On XGBSEKaplanTree that is forced to be 1 due to how it build comparables and create a kaplan-meier

**Comment by davivieirab** [comment]
Hey @kmedved , thank you for the kind message!

About the issue, could you please send us a reproducible example? It would be helpful.

As @GabrielGimenez mentioned, the `num_boost_round` is the parameter you are searching for, and you can change it when calling the `.fit` method. Its default value is set to 1000 for both `XGBSEKaplanNeighbors` and `XGBSEDebiasedBCE` model classes.

**Comment by kmedved** [comment]
I believe @GabrielGimenez explained the issue; I was using `XGBSEKaplanTree` here, so I presume that's why it rejected my attempt to set the number of rounds. I will experiment further and let you know if I have any further issues.

I hope you don't mind if I open a couple other issues re: documentation. I haven't been able to tear myself away from this package and have a bunch of questions.  Thanks again.

**Comment by gdmarmerola-loft** [comment]
Thank you very much for the feedback @kmedved ! 

We've just released the library so there's still some sharp edges. We really appreciate your feedback to help us improve.
